/**
 * Die sichtbaren Texte der öffentlichen Handbuch-Seite auf Deutsch und
 * Englisch (seit dem 26.09.2026): Kopf und Fuß, Landingpage, Wizard,
 * Konfigurator, Ergebnisseite, offene Selbstauskunft.
 *
 * Muster wie `mikroseiteTexte.ts`: `{ de, en }`, typgleich, Texte mit Werten
 * als Funktion. Die Seiten lesen sie mit `useSeitenTexte`. Das Handbuch
 * selbst steht in `inhalt.ts`, die Fragen in `fragenSprache.ts`.
 *
 * Englisch ist britisch, Fachbegriffe nach `kundenspracheGlossar.ts`. Der
 * Berater heißt „your contact person“, nie „advisor“. Keine Gedankenstriche.
 * Beträge kommen fertig formatiert herein (`euroIn`), damit das Format zur
 * Sprache passt.
 */
import type { ZweiSprachen } from "@/lib/seitenSprache";

const DE = {
  kopf: {
    zurSeite: "Zur Handbuch-Seite",
    mit: (name: string) => `mit ${name}`,
    abschnitte: "Abschnitte",
    nav: ["Handbuch", "So arbeiten wir", "Musterrechnung", "Ablauf", "Fragen"],
    aktion: "Handbuch sichern",
  },
  fuss: {
    handbuch: "Handbuch",
    konfigurator: "Konfigurator",
    musterrechnung: "Musterrechnung",
    ablauf: "Ablauf",
    rechtliches: "Rechtliches",
    impressum: "Impressum",
    datenschutz: "Datenschutz",
  },
  vertrauen: ["Keine Schufa-Abfrage", "Rund zwei Minuten", "Kostenlos und unverbindlich"],
  landing: {
    titel: (name: string) => (name ? `Ihr persönliches Immobilienhandbuch mit ${name} | OS Immobilien` : "Ihr persönliches Immobilienhandbuch | OS Immobilien"),
    beschreibung:
      "Sechs kurze Fragen, dann sehen Sie Ihren Rahmen als Modellrechnung und bekommen ein Handbuch mit Ihren Zahlen: wie die Bank rechnet und was die Steuer beiträgt.",
    augenbraue: "Kostenloses Immobilienhandbuch",
    h1a: "Erst Ihre Zahlen.",
    h1b: "Dann die passende Wohnung.",
    lead:
      "Beantworten Sie sechs kurze Fragen und sehen Sie sofort Ihren eigenen Rahmen: welche Preisspanne eine Bank Ihnen voraussichtlich zutraut und was eine Wohnung Sie im Monat nach Steuer kostet. Dazu Ihr Handbuch mit allen Zahlen.",
    nutzen: [
      "Ihr Finanzierungsrahmen als Modellrechnung",
      "Ihr monatlicher Eigenaufwand nach Steuer, mit Ihrem Steuersatz",
      "Rund 20 Seiten Handbuch, zugeschnitten auf Ihre Antworten",
    ],
    knopfRahmen: "Meinen Rahmen berechnen",
    knopfWasSteht: "Was steht im Handbuch?",
    heldAlt: "Mehrfamilienhaus mit Balkonen im Abendlicht",
    beispielKopf: "So sieht Ihr Ergebnis aus",
    beispiel: "Beispiel",
    rahmenModell: "Ihr Rahmen als Modellrechnung",
    eigenaufwandJahr1: "Eigenaufwand im Monat nach Steuer, erstes Jahr",
    beispielFuss: (kaufpreis: string) =>
      `Beispiel mit 1.000 € Überschuss im Monat, 30.000 € Eigenkapital und 100.000 € Jahresbrutto, Musterwohnung für ${kaufpreis}. Beispiel, keine Zusage.`,
    weg: {
      augenbraue: "Der richtige Weg",
      h2: "Erst Sie, dann die Bank, dann das Objekt.",
      lead: "Viele beginnen mit einem Exposé und merken erst bei der Bank, dass die Wohnung nicht zu ihnen passt. Wir drehen die Reihenfolge um.",
      umwegTitel: "Der häufige Umweg",
      umweg: ["Exposé im Portal gefunden", "Besichtigt und verliebt", "Termin bei der Bank", "Rahmen passt nicht, alles von vorn"],
      umwegSchluss: "Die Mühe steckt in einer Wohnung, die am Ende nicht zu Ihnen passt.",
      unserTitel: "Unser Weg",
      unser: ["Ihre Ziele und was die Steuer beiträgt", "Ihr Rahmen, so wie eine Bank rechnet", "Nur Wohnungen, die zu beidem passen", "Entscheidung mit offener Rechnung"],
      unserSchluss: "Sie wissen vorher, wo Sie stehen, und schauen nur an, was wirklich in Frage kommt.",
    },
    vorschau: {
      // Die Heftgrafik (`HandbuchHeft`) steht schon in der Sie-Form, auf die
      // die Handbuch-Strecke umgestellt wird.
      buch: {
        kacheln: (kapitel: number) => [
          { titel: `${kapitel} Kapitel`, unter: "Kompaktes Wissen" },
          { titel: "Rund 20 Seiten", unter: "Mit Ihren eigenen Zahlen" },
          { titel: "Direkt anwendbar", unter: "Für Ihre Entscheidung" },
        ],
        notiz: "Ihr kostenloses Immobilienhandbuch",
        beispielwerte: "Beispielwerte",
        beschreibung:
          "Ihr persönliches Immobilienhandbuch als gebundenes Heft. Vorn das Deckblatt, erstellt für den Beispielkunden Max Beispiel, dahinter aufgefächert die Seiten zu Kapitel 4, Wie eine Bank entscheidet, Kapitel 5, Ihr Rahmen, und Kapitel 8, Vermögen und der Preis des Wartens. Alle Zahlen sind Beispielwerte.",
      },
      augenbraue: "Das Handbuch",
      h2: "Das Wissen, mit dem auch unsere Berater arbeiten.",
      lead: "Kein Prospekt, sondern ein Leitfaden in Ihren Zahlen. Jedes Kapitel endet mit dem, was es für Sie bedeutet.",
      kapitelAuswahl: [
        { nr: "5", titel: "Ihr Rahmen", nutzen: "Welche Preisspanne eine Bank Ihnen voraussichtlich zutraut, gerechnet aus Ihrem Überschuss und Ihrem Eigenkapital." },
        { nr: "6", titel: "Was das Finanzamt mitträgt", nutzen: "Wie viel Ihrer Kosten über Abschreibung und Zinsen zurückkommt, mit Ihrem Steuersatz." },
        { nr: "7", titel: "Eine Wohnung, jede Zahl offen", nutzen: "Eine Musterwohnung in Ihrem Rahmen, Monat für Monat vor und nach Steuer." },
        { nr: "13", titel: "Chancen und Risiken, ehrlich gerechnet", nutzen: "Leerstand, Zinsen nach der Bindung, Sonderumlage: was passieren kann und was Sie dann tun." },
      ],
      alleKapitel: (n: number) => `Alle ${n} Kapitel anzeigen`,
      knopf: "Mein Handbuch erstellen",
    },
    wer: {
      augenbraue: "Wer dahinter steht",
      stimmenTitel: "Was Kunden über uns sagen",
      stimme: "Kundenstimme",
      stimmenFuss: "Kundenstimmen, wie sie auf osimmobilien.netlify.app veröffentlicht sind.",
      deinBerater: "Ihr Immobilienberater",
      inhaberHinweis: "Nach Ihrer Anfrage bekommen Sie einen festen Berater, der Sie vom ersten Gespräch bis nach dem Notar begleitet.",
    },
    steuer: {
      augenbraue: "Steuer",
      h2: "Was das Finanzamt jeden Monat mitträgt.",
      lead: "Die Steuer ist nicht das Produkt, sie ist der Rabatt. Wie groß er ausfällt, hängt an Ihrem Steuersatz.",
      punkte: [
        { t: "Abschreibung (AfA)", x: "Das Gebäude wird über die Jahre abgeschrieben, in unserem Modell 2 % im Jahr." },
        { t: "Zinsen", x: "Die Zinsen für das Darlehen mindern Ihre Einkünfte aus Vermietung." },
        { t: "Werbungskosten", x: "Nicht umlagefähige Kosten und Finanzierungsnebenkosten zählen mit." },
      ],
      diagrammTitel: "Eigenaufwand im ersten Jahr, je Monat",
      diagrammUnter: (kaufpreis: string) => `Modellwohnung für ${kaufpreis}, nach Jahresbrutto`,
      fussnote:
        "Modellrechnung, keine Zusage. Annahmen siehe Musterrechnung. Steuer nach Tarif 2026 mit Solidaritätszuschlag, ohne Kirchensteuer; ab rund 80.000 € Brutto greift die Gleitzone des Solidaritätszuschlags, deshalb liegt die dritte Säule leicht vorn.",
    },
    bank: {
      augenbraue: "Bankenlogik",
      h2: "Wie eine Bank entscheidet.",
      lead: "Vier Prüfsteine, in dieser Reihenfolge. Wer sie kennt, weiß vorher, wo er steht.",
      vier: [
        { t: "Bonität", x: "Zahlen Sie zuverlässig? Die Bank fragt die Schufa erst, wenn Sie zustimmen." },
        { t: "Haushaltsrechnung", x: "Was bleibt nach allen Ausgaben übrig, und wie viel davon trägt die neue Rate?" },
        { t: "Eigenkapital", x: "Die Nebenkosten des Kaufs kommen in der Regel aus eigenen Mitteln." },
        { t: "Die Wohnung", x: "Die Bank bewertet das Objekt selbst. Lage und Zustand zählen." },
      ],
      diagrammTitel: "So rechnet eine Bank: die Haushaltsrechnung als Schema",
      diagrammUnter: "Beispielhaushalt, Werte je Monat",
      fussnote: "Schema mit Beispielwerten. Jede Bank rechnet mit eigenen Pauschalen; viele setzen rund 75 % der neuen Kaltmiete an. Keine Zusage.",
      zwischenTitel: "Wie rechnet die Bank bei Ihnen?",
      zwischenUnter: "Sechs Fragen, dann sehen Sie Ihren Rahmen.",
    },
    arbeit: {
      augenbraue: "So arbeitet OS Immobilien",
      h2: "Ein Berater, vom ersten Gespräch bis nach dem Notar.",
      lead: "Wir sind Kapitalanlagevermittler, kein Makler. Sie haben einen festen Immobilienberater, der Sie durch jeden Schritt begleitet.",
      modelle: [
        { t: "Sanierter Bestand", x: "Gewachsene Lagen, vermietet, mit geprüfter Rücklage und Beschlusslage." },
        { t: "Neubau KfW 40 QNG", x: "Energieeffizient gebaut, mit eigener Abschreibungslogik." },
        { t: "WG und Co-Living", x: "Zimmerweise vermietet, höhere Miete, mehr Verwaltung." },
      ],
      bankAugenbraue: "Finanzierung",
      bankTitel: "Unsere Wohnungen kennt die Bank schon.",
      bankText:
        "Unser Finanzierungspartner hat die Objekte bereits eingewertet, die Unterlagen liegen dort vor. Das spart Rückfragen. Sie entscheiden trotzdem frei, wo Sie finanzieren.",
      wege: [
        { b: "Ihr Berater", x: "Wenn Sie schon jemanden haben" },
        { b: "Ihre Hausbank", x: "Gern auch parallel" },
        { b: "Unser Partner", x: "Objekte vorab eingewertet" },
      ],
    },
    muster: {
      augenbraue: "Musterrechnung",
      h2: "Eine Wohnung, jede Zahl offen.",
      erstesJahr: "Erstes Jahr, je Monat",
      kaltmiete: "Kaltmiete",
      kosten: "Nicht umlagefähige Kosten",
      ruecklage: "Rücklage (nicht abziehbar)",
      zins: "Zins, 4,0 %",
      tilgung: "Tilgung, 1,5 %",
      vorSteuer: "Eigenaufwand vor Steuer",
      steuerwirkung: (gs: number) => `Steuerwirkung bei rund ${gs} %`,
      nachSteuer: "Eigenaufwand nach Steuer",
      ekNebenkosten: "Eigenkapital für die Nebenkosten",
      imMonat: "im Monat nach Steuer",
      davonTilgung: "davon Tilgung, also Vermögen",
      diagrammTitel: "Wert, Restschuld und Ihr Vermögen über 30 Jahre",
      diagrammUnter: "Gleiche Wohnung, gleiche Annahmen",
      diagrammFuss: (vermoegen: string, eingesetzt: string) =>
        `Nach 30 Jahren im Modell: Vermögen in der Wohnung ${vermoegen}. Eingesetzt haben Sie bis dahin rund ${eingesetzt} (Eigenkapital, Finanzierungsnebenkosten und der laufende Eigenaufwand nach Steuer). Keine Zusage, Wertsteigerung nicht garantiert.`,
      annahmen: "Annahmen:",
      annahmenZusatz:
        "Jahresbrutto 100.000 €, Grundtarif. Rechenweg wie im OS Immobilien-Investmentrechner. Die Rücklage zahlen Sie laufend, steuerlich zählt sie erst, wenn sie ausgegeben wird.",
      zwischenTitel: "Diese Rechnung mit Ihren Zahlen?",
      zwischenUnter: "Ihr Handbuch rechnet eine Wohnung in Ihrem Rahmen, mit Ihrem Steuersatz.",
    },
    warten: {
      augenbraue: "Zeit",
      h2: "Der Preis des Wartens.",
      lead: "Dieselbe Wohnung, dasselbe Ziel in 25 Jahren. Wer später startet, hat weniger Jahre für Tilgung und Wertentwicklung.",
      grosseZahl: "weniger Vermögen in der Wohnung am Ziel, wenn Sie zehn Jahre später starten.",
      marke: "Modell, keine Prognose",
      annahmen: (kaufpreis: string, heute: string, zehn: string) =>
        `Annahmen: dieselbe Wohnung für ${kaufpreis} zu heutigem Preis und heutigen Konditionen, 4,0 % Zins, 1,5 % Tilgung, Miete und Kosten plus 2 %, Wert plus 1,5 % im Jahr, Jahresbrutto 100.000 €. Start heute: ${heute}, Start in zehn Jahren: ${zehn}.`,
      text: "Das ist kein Grund, übereilt zu kaufen. Es ist ein Grund, die Frage nicht jahrelang offen zu lassen. Ein Nein zur falschen Wohnung ist uns lieber als ein Ja, das Sie später bereuen.",
      diagrammTitel: "Vermögen in der Wohnung am Ziel, je nach Startjahr",
      diagrammUnter: "Modellwohnung, Ziel in 25 Jahren",
      fussnote: "Vereinfachung: gleiche Wohnung zu heutigem Preis und heutigen Konditionen, Annahmen wie in der Musterrechnung. Modell, keine Prognose.",
      zwischenTitel: "Wo stehen Sie heute?",
      zwischenUnter: "Rund zwei Minuten, kostenlos und ohne Schufa-Abfrage.",
    },
    ablauf: {
      augenbraue: "Ablauf",
      h2: "Vom Handbuch bis zum Schlüssel.",
      lead: "Klare Schritte, klare Reihenfolge. Sie zahlen erst, wenn der Notar die Fälligkeit mitteilt.",
      schritte: [
        { d: "Heute", t: "Ihr Handbuch", x: "Sechs Fragen, Ihr Rahmen als Modellrechnung." },
        { d: "Danach", t: "Selbstauskunft", x: "Online und ohne Verpflichtung. Aus der Schätzung wird eine Rechnung." },
        { d: "Erstgespräch", t: "Passende Wohnungen", x: "Ihr Berater bespricht Ziele und Zahlen und zeigt Ihnen nur, was passt." },
        { d: "Tag 0", t: "Reservierung", x: "Die Wohnung ist bis zum Notartermin für Sie vorgemerkt." },
        { d: "2 bis 6 Wochen", t: "Finanzierung", x: "Die Bank prüft Sie und die Wohnung." },
        { d: "14 Tage vorher", t: "Vertragsentwurf", x: "Sie bekommen den Kaufvertrag in Ruhe zum Lesen." },
        { d: "60 bis 90 Minuten", t: "Notartermin", x: "Der Vertrag wird vollständig verlesen." },
        { d: "danach", t: "Fälligkeit und Übergabe", x: "Zahlung erst nach der Fälligkeitsmitteilung, dann Übergabe und erstes Steuerjahr." },
      ],
      fussnote: "Zeitangaben sind Erfahrungswerte und keine Zusage. Die Dauer hängt vor allem an Bank und Unterlagen.",
    },
    cta: {
      augenbraue: "Ihr Handbuch",
      h2: "Sechs Fragen, dann wissen Sie, wo Sie stehen.",
      text: "Kostenlos, ohne Schufa-Abfrage, in rund zwei Minuten. Kontaktdaten erst am Ende, danach gleich Ihr Handbuch und der Weg zur Selbstauskunft.",
      knopf: "Konfigurator starten",
    },
    faq: {
      augenbraue: "Häufige Fragen",
      h2: "Was Sie vorher wissen wollen.",
      text: "Ihre Frage ist nicht dabei? Ihr Berater beantwortet sie im ersten Gespräch.",
      fragen: [
        ["Werde ich danach angerufen?", "Ja, einmal kurz. Ihr Berater meldet sich telefonisch, um Ihre Fragen zum Handbuch zu klären und mit Ihnen zu besprechen, ob und wie es für Sie weitergeht. Sie entscheiden danach selbst."],
        ["Warum ist das Handbuch kostenlos?", "Weil wir Ihnen offen und transparent zeigen möchten, welcher Investmentweg sich in Ihrer persönlichen finanziellen Situation für Sie am besten rechnet. Das Handbuch ist kostenlos und unverbindlich, und Sie entscheiden selbst, ob Sie den nächsten Schritt gehen möchten."],
        ["Wie viel Eigenkapital brauche ich?", "Das hängt immer von Ihrer persönlichen Situation ab. Ihr Handbuch rechnet Ihnen schon ein erstes Beispiel aus. Die beste Umsetzungsstrategie für Sie finden wir dann gemeinsam in einem persönlichen Gespräch."],
        [
          "Was, wenn die Wohnung einmal leer steht?",
          "Das Risiko gibt es, und wir rechnen es nicht weg. Ein Monat ohne Mieter kostet Sie die Kaltmiete, das Hausgeld läuft weiter. Deshalb planen Sie eine Rücklage auf Ihrem Konto ein, und die Verwaltung wählt die Mieter sorgfältig aus. Wie das mit Ihren Zahlen aussieht, steht in Kapitel 13 Ihres Handbuchs: Chancen und Risiken, ehrlich gerechnet.",
        ],
        ["Ist mein Rahmen eine Finanzierungszusage?", "Nein. Er ist eine Modellrechnung. Eine Zusage gibt nur eine Bank, nachdem sie Sie und die Wohnung geprüft hat."],
        ["Fragen Sie bei der Schufa an?", "Nein, weder im Konfigurator noch in der Selbstauskunft. Eine Schufa-Auskunft holt erst die finanzierende Bank ein, und nur mit Ihrer Zustimmung."],
        ["Wer sieht meine Angaben?", "OS Immobilien und der Immobilienberater, der Sie betreut. An eine Bank gehen Ihre Daten erst, wenn Sie sich für eine Finanzierung entscheiden."],
        ["Kann ich über meine Hausbank finanzieren?", "Ja. Sie können über Ihren eigenen Berater, Ihre Hausbank oder unseren Finanzierungspartner finanzieren, auch parallel anfragen."],
        ["Muss ich schon eine Wohnung im Blick haben?", "Nein, im Gegenteil. Erst klären wir Ihre Ziele und Ihren Rahmen, danach zeigen wir Ihnen nur Wohnungen, die zu beidem passen."],
        ["Ersetzt das Handbuch meinen Steuerberater?", "Nein. Es zeigt Ihnen die Mechanik. Die verbindliche Beurteilung Ihrer Steuer gehört zu Ihrem Steuerberater."],
      ] as Array<[string, string]>,
      hinweiseLabel: "Hinweise.",
      hinweise:
        "Alle Zahlen auf dieser Seite sind Modellrechnungen mit offengelegten Annahmen. Sie sind keine Zusage und kein garantiertes Ergebnis. Die steuerliche Wirkung hängt von Ihrer persönlichen Situation ab; diese Seite ersetzt keine Steuer-, Rechts- oder Anlageberatung. Sie ist kein Angebot und keine Aufforderung zum Erwerb einer Immobilie oder eines Finanzprodukts.",
    },
  },
  wizard: {
    titel: (name: string) => (name ? `Ihr Handbuch in sechs Fragen, mit ${name} | OS Immobilien` : "Ihr Handbuch in sechs Fragen | OS Immobilien"),
    beschreibung: "Sechs kurze Fragen, dann bekommen Sie Ihr persönliches Immobilienhandbuch mit Ihrem Rahmen als Modellrechnung.",
    augenbraue: "Ihr persönliches Immobilienhandbuch",
    h1: "Sechs Fragen bis zu Ihrem Rahmen.",
    lead: "Ein Klick pro Frage. Kontaktdaten erst am Ende.",
  },
  konfig: {
    buchMini: "Ihr persönliches Immobilien­handbuch",
    frage: "Frage",
    von6: "von 6",
    entsteht: "Ihr Handbuch entsteht",
    fortschritt: "Fortschritt",
    warum: "Warum wir fragen: ",
    rechenhilfe: "So rechnen Sie es kurz aus",
    gemeinsam: "Wir werden gemeinsam veranlagt",
    gemeinsamHinweis: "Dann gilt Ihr Jahresbrutto als Ihr gemeinsames Einkommen, und wir rechnen mit dem Splittingtarif.",
    zurueck: "Zurück",
    einKlickProFrage: "Ein Klick pro Frage",
    kontaktAmEnde: "Kontaktdaten erst am Ende",
    einKlickGenuegt: "Ein Klick genügt",
    titelPasst: "Ihre Angaben passen zu unseren Wohnungen.",
    titelVielleicht: "Ihre Angaben passen knapp.",
    titelNochNicht: "Noch passt es nicht. Das ist in Ordnung.",
    pillPasst: "Passt",
    pillVielleicht: "Passt vielleicht",
    pillNochNicht: "Noch nicht",
    nochNichtText:
      "Für eine vermietete Wohnung braucht es einen monatlichen Überschuss und Eigenkapital für die Nebenkosten. Beides liegt bei Ihnen gerade unter dem, was Banken meist erwarten.",
    ueGut: "Ihr monatlicher Überschuss reicht für eine Kapitalanlage.",
    ueUnbekannt: (betrag: string) => `Ihren Überschuss kennen Sie noch nicht genau. Wir rechnen vorsichtig mit ${betrag} im Monat.`,
    ueNiedrig: "Ihr Überschuss liegt unter 500 € im Monat.",
    ekGut: "Ihr Eigenkapital deckt die Kaufnebenkosten.",
    ekNiedrig: "Ihr Eigenkapital liegt unter 10.000 €.",
    steuerHoch: (gs: number) => `Bei Ihrem Steuersatz von rund ${gs} % trägt das Finanzamt spürbar mit.`,
    steuerNiedrig: (gs: number) => `Ihr Steuersatz liegt bei rund ${gs} %. Das Handbuch zeigt Ihnen, was das Finanzamt davon mitträgt.`,
    buchTrotzdem: "Ihr Handbuch bekommen Sie trotzdem.",
    buchBereit: "Ihr Handbuch ist bereit",
    buchInhalt: "Rund 20 Seiten mit Ihrem Rahmen, Ihrer Steuerwirkung und Ihrem Zeitplan.",
    knopfErhalten: "Handbuch erhalten",
    antwortenAendern: "Antworten ändern",
    rahmenImHandbuch: "Ihren Rahmen zeigt Ihnen das Handbuch.",
    wohin: "Wohin dürfen wir Ihr Handbuch schicken?",
    wohinHinweis: "Sie sehen Ihr Handbuch gleich hier auf der Seite und bekommen den Link zusätzlich per E-Mail.",
    handyHinweis: "Ihr Berater ruft Sie einmal kurz an, um Ihre Fragen zum Handbuch zu klären.",
    wirdErstellt: "Handbuch wird erstellt",
    anfordern: "Handbuch anfordern",
    kostenlos: "Kostenlos. Keine Schufa-Abfrage. Keine Weitergabe an Banken ohne Ihre Zustimmung.",
    zurueckAuswertung: "Zurück zur Auswertung",
  },
  formular: {
    vorname: "Vorname",
    nachname: "Nachname",
    email: "E-Mail",
    handy: "Handynummer",
    fehlerVorname: "Bitte geben Sie Ihren Vornamen an.",
    fehlerNachname: "Bitte geben Sie Ihren Nachnamen an.",
    fehlerEmail: "Bitte geben Sie eine gültige E-Mail-Adresse an.",
    fehlerHandy: "Bitte geben Sie Ihre Handynummer an.",
    fehlerHandyForm: "Bitte prüfen Sie die Nummer, zum Beispiel 0151 23456789 oder +49 151 23456789.",
    datenschutz: "Datenschutz",
    vollText: "Vollständigen Text anzeigen",
    pflichtHinweis: "* Pflichtfeld",
    fehlerAllgemein: "Das hat nicht geklappt. Bitte versuchen Sie es noch einmal.",
  },
  ergebnis: {
    titel: "Ihr persönliches Immobilienhandbuch | OS Immobilien",
    laedt: "Ihr Handbuch wird geladen",
    abgelaufenAugenbraue: "Link abgelaufen",
    abgelaufenTitel: (vorname: string) => `Dieser Link gilt nicht mehr${vorname ? `, ${vorname}` : ""}.`,
    abgelaufenText: "Das Handbuch ist 30 Tage abrufbar. Fordern Sie es einfach neu an, das dauert rund zwei Minuten.",
    neuAnfordern: "Handbuch neu anfordern",
    unbekanntAugenbraue: "Nicht gefunden",
    unbekanntTitel: "Dieses Handbuch gibt es nicht oder nicht mehr.",
    unbekanntText: "Prüfen Sie bitte den Link aus Ihrer E-Mail. Sie können Ihr Handbuch auch jederzeit neu anfordern.",
    zurSeite: "Zur Handbuch-Seite",
    angaben: ["Ziel", "Beruf", "Jahresbrutto", "Überschuss", "Eigenkapital", "Start", "Steuersatz", "Rahmen"],
    steuersatz: (gs: number, gemeinsam: boolean) => `rund ${gs} %${gemeinsam ? ", Splittingtarif" : ""}`,
    saPasst: "Damit rechnen wir Ihren Rahmen genau, und Ihr Berater kann Ihnen direkt passende Wohnungen vorstellen. Sie verpflichtet Sie zu nichts.",
    saVielleicht: "Ihre Angaben passen knapp. Mit der Selbstauskunft sehen wir genau, was geht. Sie verpflichtet Sie zu nichts.",
    saNochNicht: "Noch passt es nicht, und das ist in Ordnung. Wenn sich Ihre Lage ändert, ist die Selbstauskunft der erste Schritt.",
    fertig: "Fertig",
    deinHandbuch: "Ihr Handbuch",
    h1: (vorname: string) => `Ihr Handbuch ist fertig${vorname ? `, ${vorname}` : ""}.`,
    leadFrisch: "Lesen Sie es gleich hier oder speichern Sie es als PDF. Den Link dazu schicken wir Ihnen zusätzlich per E-Mail, er gilt 30 Tage.",
    leadGespeichert: "Lesen Sie es hier oder speichern Sie es als PDF. Der Link gilt 30 Tage ab der Anforderung.",
    leadOhne: "Lesen Sie es gleich hier und speichern Sie es sich am besten als PDF.",
    pdfLaeuft: "PDF wird erstellt",
    pdfSpeichern: "Als PDF speichern",
    rahmenModell: "Ihr Rahmen als Modellrechnung",
    empfohlen: (betrag: string) => `Empfohlen rund ${betrag}. Keine Finanzierungszusage. Wie er entsteht, steht in Kapitel 5.`,
    keinRahmen: "Noch kein Rahmen",
    keinRahmenText: "Mit Überschuss und Eigenkapital unter den Mindestwerten ergibt die Formel heute noch keinen Rahmen. Kapitel 5 zeigt Ihnen, woran es liegt.",
    naechster: "Ihr nächster Schritt",
    saTitel: "Selbstauskunft ausfüllen",
    saLiegtVorTitel: "Ihre Selbstauskunft liegt vor",
    saLiegtVor: "Vielen Dank. Ihr Berater meldet sich mit den nächsten Schritten bei Ihnen.",
    saAbgelaufen: "Ihr bisheriger Link zur Selbstauskunft ist abgelaufen. Über den Knopf erhalten Sie einen neuen.",
    saKnopf: "Selbstauskunft ausfüllen",
    linkAuchMail: "Den Link finden Sie auch in Ihrer E-Mail und am Ende des Handbuchs.",
    saPerMail: "Ihren persönlichen Link zur Selbstauskunft senden wir Ihnen per E-Mail. Sollte keine ankommen, meldet sich Ihr Berater bei Ihnen.",
    pdfFehlerTitel: "Das PDF ließ sich nicht erstellen",
    pdfFehlerText: "Bitte versuchen Sie es gleich noch einmal. Ihr Handbuch bleibt hier auf der Seite lesbar.",
    pdfFehlerKnopf: "Verstanden",
  },
  agenda: {
    angaben: "Ihre Angaben",
    inhalt: "Inhalt",
    beides: "Ihre Angaben und Inhalt",
    kapitelLabel: "Kapitel des Handbuchs",
  },
  saOffen: {
    titel: "Selbstauskunft ausfüllen | OS Immobilien",
    augenbraue: "Selbstauskunft",
    h1: "Aus der Schätzung wird eine Rechnung.",
    lead: "Mit der Selbstauskunft rechnen wir Ihren Rahmen genau. Sie verpflichtet Sie zu nichts und fragt nicht bei der Schufa an.",
    gesendetTitel: "Danke, Ihre Anfrage ist angekommen.",
    gesendetText: "Wir haben Ihnen gerade eine E-Mail geschickt, darin steht, wie es weitergeht. Finden Sie die Mail nicht, schauen Sie bitte auch im Spam-Ordner nach.",
    nichtGeklappt: "Das hat gerade nicht geklappt. Bitte versuchen Sie es in ein paar Minuten erneut.",
    zurSeite: "Zur Handbuch-Seite",
    wer: "Wer füllt die Selbstauskunft aus?",
    danach: "Danach geht es weiter zur Selbstauskunft, den persönlichen Link bekommen Sie zusätzlich per E-Mail. Rund 10 bis 15 Minuten, Zwischenspeichern ist möglich.",
    handyHinweis: "Ihr Berater ruft Sie einmal kurz an, um Ihre Fragen zur Selbstauskunft zu klären.",
    einenMoment: "Einen Moment",
    weiter: "Weiter zur Selbstauskunft",
    nochKeinHandbuch: "Noch kein Handbuch?",
    ersteFragen: "Erst die sechs Fragen beantworten",
  },
  saStart: {
    titel: "Selbstauskunft | OS Immobilien",
    augenbraue: "Selbstauskunft",
    laedt: "Ihre Selbstauskunft wird vorbereitet",
    liegtVorTitel: "Ihre Selbstauskunft liegt uns schon vor.",
    liegtVorText: "Möchten Sie etwas ändern, sprechen Sie einfach Ihren Berater an.",
    abgelaufenTitel: "Dieser Link gilt nicht mehr.",
    abgelaufenText: "Sie können die Selbstauskunft trotzdem ausfüllen. Dazu brauchen wir einmal kurz Ihre Kontaktdaten.",
    ausfuellen: "Selbstauskunft ausfüllen",
    zuOftText: "Die Selbstauskunft wurde heute schon mehrfach geöffnet. Nutzen Sie bitte den Link aus Ihrer E-Mail oder versuchen Sie es morgen erneut.",
    fehlerText: "Das hat gerade nicht geklappt. Bitte versuchen Sie es in ein paar Minuten erneut.",
    zurSeite: "Zur Handbuch-Seite",
  },
};

export const HANDBUCH_SEITEN_TEXTE: ZweiSprachen<typeof DE> = {
  de: DE,
  en: {
    kopf: {
      zurSeite: "To the handbook page",
      mit: (name: string) => `with ${name}`,
      abschnitte: "Sections",
      nav: ["Handbook", "How we work", "Sample calculation", "Process", "FAQ"],
      aktion: "Get your handbook",
    },
    fuss: {
      handbuch: "Handbook",
      konfigurator: "Configurator",
      musterrechnung: "Sample calculation",
      ablauf: "Process",
      rechtliches: "Legal",
      impressum: "Legal notice",
      datenschutz: "Privacy policy",
    },
    vertrauen: ["No Schufa credit check", "About two minutes", "Free and non-binding"],
    landing: {
      titel: (name: string) => (name ? `Your personal property handbook with ${name} | OS Immobilien` : "Your personal property handbook | OS Immobilien"),
      beschreibung:
        "Six short questions, then you see your budget as a model calculation and receive a handbook with your own figures: how the bank calculates and what tax contributes.",
      augenbraue: "Free property handbook",
      h1a: "Your numbers first.",
      h1b: "Then the right flat.",
      lead:
        "Answer six short questions and see your own budget straight away: the price range a bank is likely to lend you and what a flat costs you each month after tax. Plus your handbook with all the figures.",
      nutzen: [
        "Your financing budget as a model calculation",
        "Your monthly contribution after tax, at your tax rate",
        "Around 20 pages of handbook, tailored to your answers",
      ],
      knopfRahmen: "Calculate my budget",
      knopfWasSteht: "What is in the handbook?",
      heldAlt: "Apartment building with balconies in the evening light",
      beispielKopf: "This is what your result looks like",
      beispiel: "Example",
      rahmenModell: "Your budget as a model calculation",
      eigenaufwandJahr1: "Monthly contribution after tax, first year",
      beispielFuss: (kaufpreis: string) =>
        `Example with a €1,000 monthly surplus, €30,000 equity and €100,000 gross annual income, sample flat for ${kaufpreis}. Example, not a commitment.`,
      weg: {
        augenbraue: "The right way",
        h2: "You first, then the bank, then the property.",
        lead: "Many people start with a property listing and only realise at the bank that the flat does not suit them. We reverse the order.",
        umwegTitel: "The common detour",
        umweg: ["Found a listing online", "Viewed it and fell in love", "Appointment at the bank", "Budget does not fit, back to square one"],
        umwegSchluss: "All the effort goes into a flat that ends up not suiting you.",
        unserTitel: "Our way",
        unser: ["Your goals and what tax contributes", "Your budget, calculated the way a bank does", "Only flats that fit both", "A decision with the calculation disclosed"],
        unserSchluss: "You know where you stand beforehand and only look at what is really an option.",
      },
      vorschau: {
        buch: {
          kacheln: (kapitel: number) => [
            { titel: `${kapitel} chapters`, unter: "Compact knowledge" },
            { titel: "Around 20 pages", unter: "With your own figures" },
            { titel: "Directly applicable", unter: "For your decision" },
          ],
          notiz: "Your free property handbook",
          beispielwerte: "Sample figures",
          beschreibung:
            "Your personal property handbook as a bound booklet. In front the cover, prepared for the sample client Max Beispiel, behind it fanned-out pages for chapter 4, how a bank decides, chapter 5, your budget, and chapter 8, wealth and the price of waiting. All figures are sample figures.",
        },
        augenbraue: "The handbook",
        h2: "The knowledge our own team works with.",
        lead: "Not a brochure, but a guide in your own figures. Every chapter ends with what it means for you.",
        kapitelAuswahl: [
          { nr: "5", titel: "Your budget", nutzen: "The price range a bank is likely to lend you, calculated from your surplus and your equity." },
          { nr: "6", titel: "What the tax office contributes", nutzen: "How much of your costs comes back through depreciation and interest, at your tax rate." },
          { nr: "7", titel: "One flat, every figure disclosed", nutzen: "A sample flat within your budget, month by month before and after tax." },
          { nr: "13", titel: "Opportunities and risks, honestly calculated", nutzen: "Vacancy, interest after the fixed period, special levies: what can happen and what you do then." },
        ],
        alleKapitel: (n: number) => `Show all ${n} chapters`,
        knopf: "Create my handbook",
      },
      wer: {
        augenbraue: "Who is behind it",
        stimmenTitel: "What customers say about us",
        stimme: "Customer review",
        stimmenFuss: "Customer reviews as published on osimmobilien.netlify.app. Original in German.",
        deinBerater: "Your contact person",
        inhaberHinweis: "After your request you get one fixed contact person who accompanies you from the first conversation until after the notary.",
      },
      steuer: {
        augenbraue: "Tax",
        h2: "What the tax office contributes every month.",
        lead: "Tax is not the product, it is the discount. How big it is depends on your tax rate.",
        punkte: [
          { t: "Depreciation (AfA)", x: "The building is depreciated over the years, in our model by 2% a year." },
          { t: "Interest", x: "The loan interest reduces your income from letting." },
          { t: "Deductible expenses", x: "Non-recoverable costs and financing costs count too." },
        ],
        diagrammTitel: "Your contribution in the first year, per month",
        diagrammUnter: (kaufpreis: string) => `Model flat for ${kaufpreis}, by gross annual income`,
        fussnote:
          "Model calculation, not a commitment. For assumptions see the sample calculation. Income tax according to the 2026 tariff including solidarity surcharge, without church tax; from around €80,000 gross the phase-in zone of the solidarity surcharge applies, which is why the third column is slightly ahead.",
      },
      bank: {
        augenbraue: "How banks think",
        h2: "How a bank decides.",
        lead: "Four tests, in this order. If you know them, you know where you stand beforehand.",
        vier: [
          { t: "Creditworthiness", x: "Do you pay reliably? The bank only checks with Schufa once you agree." },
          { t: "Household calculation", x: "What is left after all expenses, and how much of it can cover the new instalment?" },
          { t: "Equity", x: "The purchase costs usually come from your own funds." },
          { t: "The flat", x: "The bank values the property itself. Location and condition count." },
        ],
        diagrammTitel: "How a bank calculates: the household calculation as a diagram",
        diagrammUnter: "Example household, monthly figures",
        fussnote: "Diagram with example figures. Every bank uses its own flat rates; many count about 75% of the new net cold rent. Not a commitment.",
        zwischenTitel: "How would the bank calculate for you?",
        zwischenUnter: "Six questions, then you see your budget.",
      },
      arbeit: {
        augenbraue: "How OS Immobilien works",
        h2: "One contact person, from the first conversation until after the notary.",
        lead: "We are an investment property intermediary, not an estate agent. You have one fixed contact person who accompanies you through every step.",
        modelle: [
          { t: "Renovated existing buildings", x: "Established locations, let, with a checked reserve and owners' resolutions." },
          { t: "New build KfW 40 QNG", x: "Built to be energy efficient, with its own depreciation logic." },
          { t: "Shared flats and co-living", x: "Let room by room, higher rent, more management." },
        ],
        bankAugenbraue: "Financing",
        bankTitel: "The bank already knows our flats.",
        bankText:
          "Our financing partner has already valued the properties and has the documents. That saves follow-up questions. You are still free to decide where you finance.",
        wege: [
          { b: "Your own adviser", x: "If you already have one" },
          { b: "Your own bank", x: "In parallel too" },
          { b: "Our partner", x: "Properties valued in advance" },
        ],
      },
      muster: {
        augenbraue: "Sample calculation",
        h2: "One flat, every figure disclosed.",
        erstesJahr: "First year, per month",
        kaltmiete: "Net cold rent",
        kosten: "Non-recoverable costs",
        ruecklage: "Maintenance reserve (not deductible)",
        zins: "Interest, 4.0%",
        tilgung: "Repayment, 1.5%",
        vorSteuer: "Your contribution before tax",
        steuerwirkung: (gs: number) => `Tax effect at about ${gs}%`,
        nachSteuer: "Your contribution after tax",
        ekNebenkosten: "Equity for the purchase costs",
        imMonat: "per month after tax",
        davonTilgung: "of which repayment, i.e. wealth",
        diagrammTitel: "Value, remaining debt and your equity over 30 years",
        diagrammUnter: "Same flat, same assumptions",
        diagrammFuss: (vermoegen: string, eingesetzt: string) =>
          `After 30 years in the model: equity in the flat ${vermoegen}. By then you will have put in about ${eingesetzt} (equity, financing costs and your ongoing contribution after tax). Not a commitment, increase in value not guaranteed.`,
        annahmen: "Assumptions:",
        annahmenZusatz:
          "Gross annual income €100,000, basic tariff. Calculated as in the OS Immobilien investment calculator. You pay the reserve continuously; for tax purposes it only counts once it is spent.",
        zwischenTitel: "This calculation with your figures?",
        zwischenUnter: "Your handbook calculates a flat within your budget, at your tax rate.",
      },
      warten: {
        augenbraue: "Time",
        h2: "The price of waiting.",
        lead: "The same flat, the same goal in 25 years. If you start later, you have fewer years for repayment and growth in value.",
        grosseZahl: "less equity in the flat at the goal if you start ten years later.",
        marke: "Model, not a forecast",
        annahmen: (kaufpreis: string, heute: string, zehn: string) =>
          `Assumptions: the same flat for ${kaufpreis} at today's price and terms, 4.0% interest, 1.5% repayment, rent and costs plus 2%, value plus 1.5% a year, gross annual income €100,000. Start today: ${heute}, start in ten years: ${zehn}.`,
        text: "That is no reason to buy in a hurry. It is a reason not to leave the question open for years. We would rather hear no to the wrong flat than a yes you regret later.",
        diagrammTitel: "Equity in the flat at the goal, by starting year",
        diagrammUnter: "Model flat, goal in 25 years",
        fussnote: "Simplification: the same flat at today's price and terms, assumptions as in the sample calculation. Model, not a forecast.",
        zwischenTitel: "Where do you stand today?",
        zwischenUnter: "About two minutes, free and without a Schufa check.",
      },
      ablauf: {
        augenbraue: "Process",
        h2: "From the handbook to the keys.",
        lead: "Clear steps, clear order. You only pay once the notary confirms payment is due.",
        schritte: [
          { d: "Today", t: "Your handbook", x: "Six questions, your budget as a model calculation." },
          { d: "Afterwards", t: "Self-disclosure", x: "Online and without obligation. The estimate becomes a calculation." },
          { d: "First meeting", t: "Suitable flats", x: "Your contact person discusses goals and figures and only shows you what fits." },
          { d: "Day 0", t: "Reservation", x: "The flat is held for you until the notary appointment." },
          { d: "2 to 6 weeks", t: "Financing", x: "The bank assesses you and the flat." },
          { d: "14 days before", t: "Draft contract", x: "You receive the purchase contract to read at your own pace." },
          { d: "60 to 90 minutes", t: "Notary appointment", x: "The contract is read out in full." },
          { d: "afterwards", t: "Payment and handover", x: "You only pay after the notice that payment is due, then handover and your first tax year." },
        ],
        fussnote: "Timings are based on experience and are not a commitment. The duration depends mainly on the bank and the documents.",
      },
      cta: {
        augenbraue: "Your handbook",
        h2: "Six questions, then you know where you stand.",
        text: "Free, without a Schufa check, in about two minutes. Contact details only at the end, then your handbook straight away and the way to the self-disclosure.",
        knopf: "Start the configurator",
      },
      faq: {
        augenbraue: "FAQ",
        h2: "What you want to know beforehand.",
        text: "Your question is not here? Your contact person will answer it in the first conversation.",
        fragen: [
          ["Will I get a call afterwards?", "Yes, once and briefly. Your contact person calls you to answer your questions about the handbook and to discuss whether and how you would like to continue. You decide for yourself afterwards."],
          ["Why is the handbook free?", "Because we want to show you openly and transparently which investment route works best in your personal financial situation. The handbook is free and non-binding, and you decide for yourself whether to take the next step."],
          ["How much equity do I need?", "That always depends on your personal situation. Your handbook already calculates a first example for you. We then find the best strategy for you together in a personal conversation."],
          [
            "What if the flat is empty for a while?",
            "The risk exists, and we do not calculate it away. A month without a tenant costs you the net cold rent, and the service charge continues. That is why you plan a reserve in your account, and the management selects tenants carefully. Chapter 13 of your handbook shows what this looks like with your figures: opportunities and risks, honestly calculated.",
          ],
          ["Is my budget a financing commitment?", "No. It is a model calculation. Only a bank can give a commitment, after assessing you and the flat."],
          ["Do you run a Schufa credit check?", "No, neither in the configurator nor in the self-disclosure. Only the financing bank requests a Schufa report, and only with your consent."],
          ["Who sees my details?", "OS Immobilien and your contact person who looks after you. Your data only goes to a bank once you decide on a financing."],
          ["Can I finance through my own bank?", "Yes. You can finance through your own adviser, your own bank or our financing partner, and ask in parallel."],
          ["Do I need to have a flat in mind already?", "No, quite the opposite. First we clarify your goals and your budget, then we only show you flats that fit both."],
          ["Does the handbook replace my tax adviser?", "No. It shows you the mechanics. The binding assessment of your tax is a matter for your tax adviser."],
        ] as Array<[string, string]>,
        hinweiseLabel: "Notes.",
        hinweise:
          "All figures on this page are model calculations with disclosed assumptions. They are not a commitment and not a guaranteed result. The tax effect depends on your personal situation; this page does not replace tax, legal or investment advice. It is neither an offer nor a solicitation to buy a property or a financial product.",
      },
    },
    wizard: {
      titel: (name: string) => (name ? `Your handbook in six questions, with ${name} | OS Immobilien` : "Your handbook in six questions | OS Immobilien"),
      beschreibung: "Six short questions, then you receive your personal property handbook with your budget as a model calculation.",
      augenbraue: "Your personal property handbook",
      h1: "Six questions to your budget.",
      lead: "One click per question. Contact details only at the end.",
    },
    konfig: {
      buchMini: "Your personal property handbook",
      frage: "Question",
      von6: "of 6",
      entsteht: "Your handbook is taking shape",
      fortschritt: "Progress",
      warum: "Why we ask: ",
      rechenhilfe: "How to work it out quickly",
      gemeinsam: "We are assessed jointly for tax",
      gemeinsamHinweis: "Then your gross annual income counts as your joint income, and we calculate with the splitting tariff.",
      zurueck: "Back",
      einKlickProFrage: "One click per question",
      kontaktAmEnde: "Contact details only at the end",
      einKlickGenuegt: "One click is enough",
      titelPasst: "Your details fit our flats.",
      titelVielleicht: "Your details are a close fit.",
      titelNochNicht: "It is not a fit yet. That is fine.",
      pillPasst: "Fits",
      pillVielleicht: "May fit",
      pillNochNicht: "Not yet",
      nochNichtText:
        "A rented flat needs a monthly surplus and equity for the purchase costs. Both are currently below what banks usually expect.",
      ueGut: "Your monthly surplus is enough for an investment property.",
      ueUnbekannt: (betrag: string) => `You do not know your surplus exactly yet. We calculate cautiously with ${betrag} a month.`,
      ueNiedrig: "Your surplus is below €500 a month.",
      ekGut: "Your equity covers the incidental purchase costs.",
      ekNiedrig: "Your equity is below €10,000.",
      steuerHoch: (gs: number) => `At your tax rate of about ${gs}%, the tax office contributes noticeably.`,
      steuerNiedrig: (gs: number) => `Your tax rate is about ${gs}%. The handbook shows you what the tax office contributes.`,
      buchTrotzdem: "You still get your handbook.",
      buchBereit: "Your handbook is ready",
      buchInhalt: "Around 20 pages with your budget, your tax effect and your timeline.",
      knopfErhalten: "Get handbook",
      antwortenAendern: "Change answers",
      rahmenImHandbuch: "The handbook shows you your budget.",
      wohin: "Where should we send your handbook?",
      wohinHinweis: "You will see your handbook right here on the page and also receive the link by email.",
      handyHinweis: "Your contact person will call you once, briefly, to answer your questions about the handbook.",
      wirdErstellt: "Creating your handbook",
      anfordern: "Request handbook",
      kostenlos: "Free. No Schufa check. Nothing is passed on to banks without your consent.",
      zurueckAuswertung: "Back to the evaluation",
    },
    formular: {
      vorname: "First name",
      nachname: "Last name",
      email: "Email",
      handy: "Mobile number",
      fehlerVorname: "Please enter your first name.",
      fehlerNachname: "Please enter your last name.",
      fehlerEmail: "Please enter a valid email address.",
      fehlerHandy: "Please enter your mobile number.",
      fehlerHandyForm: "Please check the number, for example +49 151 23456789 or 0151 23456789.",
      datenschutz: "Privacy policy",
      vollText: "Show full text",
      pflichtHinweis: "* Required field",
      fehlerAllgemein: "That did not work. Please try again.",
    },
    ergebnis: {
      titel: "Your personal property handbook | OS Immobilien",
      laedt: "Loading your handbook",
      abgelaufenAugenbraue: "Link expired",
      abgelaufenTitel: (vorname: string) => `This link is no longer valid${vorname ? `, ${vorname}` : ""}.`,
      abgelaufenText: "The handbook can be accessed for 30 days. Simply request it again, it takes about two minutes.",
      neuAnfordern: "Request the handbook again",
      unbekanntAugenbraue: "Not found",
      unbekanntTitel: "This handbook does not exist or no longer exists.",
      unbekanntText: "Please check the link in your email. You can also request your handbook again at any time.",
      zurSeite: "To the handbook page",
      angaben: ["Goal", "Occupation", "Gross annual income", "Surplus", "Equity", "Start", "Tax rate", "Budget"],
      steuersatz: (gs: number, gemeinsam: boolean) => `about ${gs}%${gemeinsam ? ", joint assessment" : ""}`,
      saPasst: "It lets us calculate your budget precisely, and your contact person can present suitable flats straight away. It does not commit you to anything.",
      saVielleicht: "Your details are a close fit. The self-disclosure shows us exactly what is possible. It does not commit you to anything.",
      saNochNicht: "It is not a fit yet, and that is fine. When your situation changes, the self-disclosure is the first step.",
      fertig: "Done",
      deinHandbuch: "Your handbook",
      h1: (vorname: string) => `Your handbook is ready${vorname ? `, ${vorname}` : ""}.`,
      leadFrisch: "Read it right here or save it as a PDF. We are also sending you the link by email; it is valid for 30 days.",
      leadGespeichert: "Read it here or save it as a PDF. The link is valid for 30 days from your request.",
      leadOhne: "Read it right here, and ideally save it as a PDF.",
      pdfLaeuft: "Creating PDF",
      pdfSpeichern: "Save as PDF",
      rahmenModell: "Your budget as a model calculation",
      empfohlen: (betrag: string) => `Recommended about ${betrag}. Not a financing commitment. Chapter 5 explains how it is calculated.`,
      keinRahmen: "No budget yet",
      keinRahmenText: "With surplus and equity below the minimum values, the formula does not yield a budget yet. Chapter 5 shows you why.",
      naechster: "Your next step",
      saTitel: "Complete the self-disclosure",
      saLiegtVorTitel: "Your self-disclosure has been received",
      saLiegtVor: "Thank you. Your contact person will get in touch with you about the next steps.",
      saAbgelaufen: "Your previous link to the self-disclosure has expired. Use the button to get a new one.",
      saKnopf: "Complete self-disclosure",
      linkAuchMail: "You will also find the link in your email and at the end of the handbook.",
      saPerMail: "We will send you your personal link to the self-disclosure by email. If none arrives, your contact person will get in touch with you.",
      pdfFehlerTitel: "The PDF could not be created",
      pdfFehlerText: "Please try again in a moment. Your handbook remains readable here on the page.",
      pdfFehlerKnopf: "Got it",
    },
    agenda: {
      angaben: "Your details",
      inhalt: "Contents",
      beides: "Your details and contents",
      kapitelLabel: "Chapters of the handbook",
    },
    saOffen: {
      titel: "Complete your self-disclosure | OS Immobilien",
      augenbraue: "Self-disclosure",
      h1: "The estimate becomes a calculation.",
      lead: "With the self-disclosure (Selbstauskunft) we calculate your budget precisely. It does not commit you to anything and does not involve a Schufa check.",
      gesendetTitel: "Thank you, your request has arrived.",
      gesendetText: "We have just sent you an email explaining what happens next. If you cannot find the email, please also check your spam folder.",
      nichtGeklappt: "That did not work just now. Please try again in a few minutes.",
      zurSeite: "To the handbook page",
      wer: "Who is completing the self-disclosure?",
      danach: "Then you continue to the self-disclosure, and you also receive your personal link by email. About 10 to 15 minutes, you can save and continue later.",
      handyHinweis: "Your contact person will call you once, briefly, to answer your questions about the self-disclosure.",
      einenMoment: "One moment",
      weiter: "Continue to the self-disclosure",
      nochKeinHandbuch: "No handbook yet?",
      ersteFragen: "Answer the six questions first",
    },
    saStart: {
      titel: "Self-disclosure | OS Immobilien",
      augenbraue: "Self-disclosure",
      laedt: "Preparing your self-disclosure",
      liegtVorTitel: "We already have your self-disclosure.",
      liegtVorText: "If you would like to change anything, simply contact your contact person.",
      abgelaufenTitel: "This link is no longer valid.",
      abgelaufenText: "You can still complete the self-disclosure. For that we briefly need your contact details once.",
      ausfuellen: "Complete self-disclosure",
      zuOftText: "The self-disclosure has already been opened several times today. Please use the link in your email or try again tomorrow.",
      fehlerText: "That did not work just now. Please try again in a few minutes.",
      zurSeite: "To the handbook page",
    },
  },
};

export type HandbuchSeitenTexte = typeof DE;
