
-- ═══════════════════════════════════════════════════════════════
-- DEMO-KONTAKTE: 40 realistische Kunden über alle Pipeline-Phasen
-- Alle markiert mit meta.demo = true für spätere Löschung
-- Berater: Christian Peetz (Haupttest-Account)
-- ═══════════════════════════════════════════════════════════════

-- ═══ ERSTGESPRÄCH (10) – View: Kontakte ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Maximilian', 'Weber', '+49 171 2345678', 'max.weber@example.de', 'Meta Kampagne', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-22","setterTerminUhrzeit":"10:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Sehr interessiert an Kapitalanlage. Eigenkapital ca. 30.000€ vorhanden. Möchte Altersvorsorge aufbauen."}'::jsonb, 'Leopoldstr.', '42', '80802', 'München'),
('Sophie', 'Müller', '+49 172 3456789', 'sophie.mueller@example.de', 'Google Ads', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-23","setterTerminUhrzeit":"14:30","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Ehepaar, beide berufstätig. Suchen sichere Geldanlage. Zeitrahmen: 3 Monate."}'::jsonb, 'Kaiserstr.', '7', '60311', 'Frankfurt'),
('Alexander', 'Schmidt', '+49 173 4567890', 'a.schmidt@example.de', 'Empfehlung', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-24","setterTerminUhrzeit":"11:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Empfohlen von Bestandskunde Hartmann. IT-Branche, gutes Einkommen."}'::jsonb, 'Friedrichstr.', '118', '10117', 'Berlin'),
('Laura', 'Fischer', '+49 174 5678901', 'laura.fischer@example.de', 'Instagram', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-25","setterTerminUhrzeit":"16:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Selbständige Designerin, 32 Jahre. Will in Immobilien diversifizieren."}'::jsonb, 'Schillerstr.', '23', '70173', 'Stuttgart'),
('Tobias', 'Wagner', '+49 175 6789012', 'tobias.wagner@example.de', 'Website', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"website","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-26","setterTerminUhrzeit":"09:30","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Beamter, sichere Einkommenssituation. Möchte Steuervorteile nutzen."}'::jsonb, 'Goethestr.', '55', '40237', 'Düsseldorf'),
('Julia', 'Becker', '+49 176 7890123', 'julia.becker@example.de', 'LinkedIn', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-27","setterTerminUhrzeit":"13:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Marketing-Managerin bei DAX-Konzern. Bereits Eigentumswohnung vorhanden."}'::jsonb, 'Bahnhofstr.', '9', '50667', 'Köln'),
('Markus', 'Hoffmann', '+49 177 8901234', 'markus.hoffmann@example.de', 'Netzwerk', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-28","setterTerminUhrzeit":"15:30","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Ingenieur bei BMW, 45 Jahre. Möchte für Kinder vorsorgen."}'::jsonb, 'Maximilianstr.', '31', '80539', 'München'),
('Anna', 'Schäfer', '+49 178 9012345', 'anna.schaefer@example.de', 'Facebook', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-29","setterTerminUhrzeit":"10:30","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Ärztin, sehr analytisch. Will Rendite-Risiko-Verhältnis genau verstehen."}'::jsonb, 'Königsallee', '14', '40212', 'Düsseldorf'),
('Daniel', 'Koch', '+49 179 0123456', 'daniel.koch@example.de', 'Meta Kampagne', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-30","setterTerminUhrzeit":"17:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Junger Unternehmer, 28 Jahre. Hohe Risikobereitschaft. EK 50.000€."}'::jsonb, 'Hafenstr.', '3', '20459', 'Hamburg'),
('Lisa', 'Bauer', '+49 170 1234567', 'lisa.bauer@example.de', 'Google Ads', 'Christian Peetz', 'kontaktiert', '', '', '{"demo":true,"pipelineStufe":"erstgespraech","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterTerminDatum":"2026-03-31","setterTerminUhrzeit":"12:00","setterCloser":"Christian Peetz","setterChecklisteDone":true,"setterSkriptNotizen":"Lehrerin, 38 Jahre. Verbeamtet. Stabiles Einkommen, erste Immobilie."}'::jsonb, 'Mozartstr.', '8', '90402', 'Nürnberg');

-- ═══ BONITÄTSUNTERLAGEN (5) – View: Neukunden ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Stefan', 'Richter', '+49 171 1112233', 'stefan.richter@example.de', 'Empfehlung', 'Christian Peetz', 'qualifiziert', '', 'positiv', '{"demo":true,"pipelineStufe":"bonitaetsunterlagen","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5200,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":50,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":950,"lebenshaltung":600,"privateKV":0,"zinsTilgung":0,"autokredite":250,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":100}}'::jsonb, 'Berliner Str.', '45', '81675', 'München'),
('Katharina', 'Wolf', '+49 172 2223344', 'k.wolf@example.de', 'Meta Kampagne', 'Christian Peetz', 'qualifiziert', '', 'positiv', '{"demo":true,"pipelineStufe":"bonitaetsunterlagen","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4800,"selbstaendig":0,"renten":0,"mieteinnahmen":600,"zinsen":0,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":0,"lebenshaltung":550,"privateKV":0,"zinsTilgung":450,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Schwabing Ring', '12', '80796', 'München'),
('Patrick', 'Zimmermann', '+49 173 3334455', 'p.zimmermann@example.de', 'Google Ads', 'Christian Peetz', 'qualifiziert', '', 'neutral', '{"demo":true,"pipelineStufe":"bonitaetsunterlagen","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":3800,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":200,"kindergeld":438},"ausgaben":{"miete":780,"lebenshaltung":500,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":150,"sonstigeKredite":0,"unterhalt":0,"sonstige":50}}'::jsonb, 'Augustenstr.', '78', '80333', 'München'),
('Marie', 'Braun', '+49 174 4445566', 'marie.braun@example.de', 'Website', 'Christian Peetz', 'qualifiziert', '', 'positiv', '{"demo":true,"pipelineStufe":"bonitaetsunterlagen","leadTyp":"website","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":6100,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":120,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":1100,"lebenshaltung":700,"privateKV":0,"zinsTilgung":0,"autokredite":300,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":150}}'::jsonb, 'Isartor Platz', '3', '80331', 'München'),
('Thomas', 'Hartmann', '+49 175 5556677', 'thomas.hartmann@example.de', 'Netzwerk', 'Christian Peetz', 'qualifiziert', '', 'positiv', '{"demo":true,"pipelineStufe":"bonitaetsunterlagen","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":7500,"selbstaendig":0,"renten":0,"mieteinnahmen":850,"zinsen":200,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":0,"lebenshaltung":800,"privateKV":350,"zinsTilgung":600,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":200}}'::jsonb, 'Prinzregentenstr.', '21', '81675', 'München');

-- ═══ OBJEKTAUSWAHL (5) – View: Neukunden ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Sarah', 'Krüger', '+49 176 6667788', 's.krueger@example.de', 'Meta Kampagne', 'Christian Peetz', 'qualifiziert', '', 0, 'positiv', '{"demo":true,"pipelineStufe":"objektauswahl","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4200,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":850,"lebenshaltung":550,"privateKV":0,"zinsTilgung":0,"autokredite":200,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Ludwigstr.', '16', '80539', 'München'),
('Michael', 'Lange', '+49 177 7778899', 'michael.lange@example.de', 'Empfehlung', 'Christian Peetz', 'qualifiziert', '', 0, 'positiv', '{"demo":true,"pipelineStufe":"objektauswahl","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5800,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":100,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":1200,"lebenshaltung":650,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":120}}'::jsonb, 'Rosenstr.', '4', '80331', 'München'),
('Christina', 'Schmitt', '+49 178 8889900', 'c.schmitt@example.de', 'Google Ads', 'Christian Peetz', 'qualifiziert', '', 0, 'positiv', '{"demo":true,"pipelineStufe":"objektauswahl","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4500,"selbstaendig":800,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":900,"lebenshaltung":500,"privateKV":280,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":60}}'::jsonb, 'Arnulfstr.', '60', '80335', 'München'),
('Andreas', 'Werner', '+49 179 9990011', 'a.werner@example.de', 'Website', 'Christian Peetz', 'qualifiziert', '', 0, 'neutral', '{"demo":true,"pipelineStufe":"objektauswahl","leadTyp":"website","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":3600,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":150,"kindergeld":438},"ausgaben":{"miete":750,"lebenshaltung":480,"privateKV":0,"zinsTilgung":0,"autokredite":180,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":50}}'::jsonb, 'Sendlinger Str.', '30', '80331', 'München'),
('Elena', 'Meier', '+49 170 0001122', 'elena.meier@example.de', 'Instagram', 'Christian Peetz', 'qualifiziert', '', 0, 'positiv', '{"demo":true,"pipelineStufe":"objektauswahl","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5500,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":80,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":1050,"lebenshaltung":600,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":350,"sonstige":100}}'::jsonb, 'Nymphenburger Str.', '88', '80636', 'München');

-- ═══ RESERVIERUNG (3) – View: Abwicklung ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Florian', 'Schulz', '+49 171 1010101', 'f.schulz@example.de', 'Meta Kampagne', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 189000, 'positiv', '{"demo":true,"pipelineStufe":"reservierung","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-03-10","einkuenfte":{"gehalt":5000,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":900,"lebenshaltung":550,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Dachauer Str.', '15', '80335', 'München'),
('Vanessa', 'Maier', '+49 172 2020202', 'v.maier@example.de', 'Google Ads', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 165000, 'positiv', '{"demo":true,"pipelineStufe":"reservierung","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-03-12","einkuenfte":{"gehalt":4600,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":50,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":850,"lebenshaltung":500,"privateKV":0,"zinsTilgung":0,"autokredite":220,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":60}}'::jsonb, 'Theresienstr.', '33', '80333', 'München'),
('Sebastian', 'Keller', '+49 173 3030303', 's.keller@example.de', 'Empfehlung', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 210000, 'positiv', '{"demo":true,"pipelineStufe":"reservierung","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-03-15","einkuenfte":{"gehalt":6200,"selbstaendig":0,"renten":0,"mieteinnahmen":600,"zinsen":0,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":0,"lebenshaltung":700,"privateKV":0,"zinsTilgung":500,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":150}}'::jsonb, 'Candidstr.', '7', '81543', 'München');

-- ═══ FINANZIERUNG (3) – View: Abwicklung ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Natalie', 'Frank', '+49 174 4040404', 'n.frank@example.de', 'Website', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 195000, 'positiv', '{"demo":true,"pipelineStufe":"finanzierung","leadTyp":"website","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-02-20","finanzierungsStatus":"offen","finanzierungsBank":"Sparkasse","finanzierungsSumme":175000,"finanzierungsZins":"3,45%","finanzierungsTilgung":"2%","finanzierungsLaufzeit":"15 Jahre","einkuenfte":{"gehalt":5100,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":920,"lebenshaltung":580,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":90}}'::jsonb, 'Türkenstr.', '22', '80333', 'München'),
('Oliver', 'Berger', '+49 175 5050505', 'o.berger@example.de', 'Netzwerk', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 178000, 'positiv', '{"demo":true,"pipelineStufe":"finanzierung","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-02-25","finanzierungsStatus":"bestaetigt","finanzierungsBank":"HypoVereinsbank","finanzierungsSumme":160000,"finanzierungsZins":"3,25%","finanzierungsTilgung":"2,5%","finanzierungsLaufzeit":"20 Jahre","einkuenfte":{"gehalt":5800,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":120,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":1100,"lebenshaltung":650,"privateKV":0,"zinsTilgung":0,"autokredite":280,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":100}}'::jsonb, 'Hohenzollernstr.', '41', '80796', 'München'),
('Jennifer', 'Roth', '+49 176 6060606', 'j.roth@example.de', 'Meta Kampagne', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 225000, 'positiv', '{"demo":true,"pipelineStufe":"finanzierung","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-02-28","finanzierungsStatus":"offen","finanzierungsBank":"DSL Bank","finanzierungsSumme":200000,"finanzierungsZins":"3,55%","finanzierungsTilgung":"2%","finanzierungsLaufzeit":"15 Jahre","einkuenfte":{"gehalt":6500,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":300,"kindergeld":876},"ausgaben":{"miete":1300,"lebenshaltung":750,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":200,"sonstigeKredite":0,"unterhalt":0,"sonstige":120}}'::jsonb, 'Brienner Str.', '50', '80333', 'München');

-- ═══ NOTAR (2) – View: Abwicklung ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Matthias', 'Winkler', '+49 177 7070707', 'm.winkler@example.de', 'Empfehlung', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 198000, 'positiv', '{"demo":true,"pipelineStufe":"notar","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-02-05","finanzierungsStatus":"bestaetigt","finanzierungsBank":"Commerzbank","finanzierungsSumme":178000,"notarTermin":"2026-04-10","notarUhrzeit":"14:00","notarName":"Dr. Friedrich Mayr","notarAdresse":"Maximilianstr. 35, 80539 München","einkuenfte":{"gehalt":5400,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":80,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":950,"lebenshaltung":600,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Viktualienmarkt', '5', '80331', 'München'),
('Sabrina', 'Lorenz', '+49 178 8080808', 's.lorenz@example.de', 'Google Ads', 'Christian Peetz', 'qualifiziert', 'MFH Memmingen', 172000, 'positiv', '{"demo":true,"pipelineStufe":"notar","leadTyp":"google","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-02-10","finanzierungsStatus":"bestaetigt","finanzierungsBank":"ING","finanzierungsSumme":155000,"notarTermin":"2026-04-15","notarUhrzeit":"10:30","notarName":"RA Christine Held","notarAdresse":"Leopoldstr. 21, 80802 München","einkuenfte":{"gehalt":4900,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":880,"lebenshaltung":520,"privateKV":0,"zinsTilgung":0,"autokredite":200,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":70}}'::jsonb, 'Rumfordstr.', '18', '80469', 'München');

-- ═══ AFTER SALES (1) – View: Abwicklung ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Jan', 'Peters', '+49 179 9090909', 'jan.peters@example.de', 'Meta Kampagne', 'Christian Peetz', 'kunde', 'MFH Memmingen', 205000, 'positiv', '{"demo":true,"pipelineStufe":"aftersales","leadTyp":"meta","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-01-15","finanzierungsStatus":"bestaetigt","finanzierungsBank":"Volksbank","notarTermin":"2026-03-01","notarUhrzeit":"11:00","notarName":"Notar Hans Gruber","notarAdresse":"Salvatorstr. 10, 80333 München","einkuenfte":{"gehalt":5600,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":100,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":1050,"lebenshaltung":650,"privateKV":0,"zinsTilgung":0,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":100}}'::jsonb, 'Residenzstr.', '27', '80333', 'München');

-- ═══ ABRECHNUNG (1) – View: Abwicklung ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Franziska', 'Seidel', '+49 170 1010101', 'f.seidel@example.de', 'Empfehlung', 'Christian Peetz', 'kunde', 'MFH Memmingen', 188000, 'positiv', '{"demo":true,"pipelineStufe":"abrechnung","leadTyp":"manuell","setter":"Lisa Kern","setterTerminGebucht":true,"setterChecklisteDone":true,"setterCloser":"Christian Peetz","reservierungsDatum":"2026-01-05","finanzierungsStatus":"bestaetigt","finanzierungsBank":"DKB","notarTermin":"2026-02-15","notarUhrzeit":"09:00","notarName":"Dr. Petra Schuster","notarAdresse":"Frauenstr. 12, 80469 München","einkuenfte":{"gehalt":4300,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":200,"kindergeld":438},"ausgaben":{"miete":820,"lebenshaltung":500,"privateKV":0,"zinsTilgung":0,"autokredite":180,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":60}}'::jsonb, 'Müllerstr.', '44', '80469', 'München');

-- ═══ BESTANDSKUNDEN / ABGESCHLOSSEN (10) – View: Bestandskunden ═══
INSERT INTO kontakte (vorname, nachname, telefon, email, quelle, berater, status, objekt, kaufpreis, finanzierbarkeit, meta, strasse, hausnummer, plz, ort) VALUES
('Robert', 'Klein', '+49 171 2020202', 'r.klein@example.de', 'Meta Kampagne', 'Christian Peetz', 'kunde', 'MFH Memmingen', 195000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"meta","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5200,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":0,"lebenshaltung":600,"privateKV":0,"zinsTilgung":500,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Herzogstr.', '11', '80803', 'München'),
('Hannah', 'Brandt', '+49 172 3030303', 'h.brandt@example.de', 'Google Ads', 'Christian Peetz', 'kunde', 'MFH Memmingen', 178000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"google","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4700,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":60,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":0,"lebenshaltung":550,"privateKV":0,"zinsTilgung":420,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":70}}'::jsonb, 'Elisabethstr.', '25', '80796', 'München'),
('Tim', 'Walter', '+49 173 4040404', 't.walter@example.de', 'Empfehlung', 'Christian Peetz', 'kunde', 'MFH Memmingen', 210000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"manuell","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":6800,"selbstaendig":0,"renten":0,"mieteinnahmen":850,"zinsen":150,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":0,"lebenshaltung":750,"privateKV":380,"zinsTilgung":800,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":120}}'::jsonb, 'Georgenstr.', '37', '80799', 'München'),
('Lena', 'Schreiber', '+49 174 5050505', 'l.schreiber@example.de', 'Website', 'Christian Peetz', 'kunde', 'MFH Memmingen', 165000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"website","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4100,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":0,"lebenshaltung":500,"privateKV":0,"zinsTilgung":380,"autokredite":200,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":60}}'::jsonb, 'Schellingstr.', '52', '80799', 'München'),
('Philipp', 'Engel', '+49 175 6060606', 'p.engel@example.de', 'LinkedIn', 'Christian Peetz', 'kunde', 'MFH Memmingen', 225000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"manuell","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":7200,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":200,"sonstige":0,"kindergeld":0},"ausgaben":{"miete":0,"lebenshaltung":800,"privateKV":420,"zinsTilgung":700,"autokredite":350,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":150}}'::jsonb, 'Amalienstr.', '19', '80333', 'München'),
('Nina', 'Haas', '+49 176 7070707', 'n.haas@example.de', 'Meta Kampagne', 'Christian Peetz', 'kunde', 'MFH Memmingen', 189000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"meta","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4500,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":0,"lebenshaltung":580,"privateKV":0,"zinsTilgung":450,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":300,"sonstige":80}}'::jsonb, 'Akademiestr.', '6', '80799', 'München'),
('Kevin', 'Albrecht', '+49 177 8080808', 'k.albrecht@example.de', 'Netzwerk', 'Christian Peetz', 'kunde', 'MFH Memmingen', 198000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"manuell","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5500,"selbstaendig":0,"renten":0,"mieteinnahmen":600,"zinsen":80,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":0,"lebenshaltung":650,"privateKV":0,"zinsTilgung":550,"autokredite":0,"privatkredite":180,"sonstigeKredite":0,"unterhalt":0,"sonstige":90}}'::jsonb, 'Veterinärstr.', '14', '80539', 'München'),
('Marina', 'Dietrich', '+49 178 9090909', 'm.dietrich@example.de', 'Facebook', 'Christian Peetz', 'kunde', 'MFH Memmingen', 172000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"meta","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":4800,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":250,"kindergeld":0},"ausgaben":{"miete":0,"lebenshaltung":520,"privateKV":0,"zinsTilgung":400,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":70}}'::jsonb, 'Kaulbachstr.', '29', '80539', 'München'),
('Dominik', 'Schwarz', '+49 179 1010101', 'd.schwarz@example.de', 'Google Ads', 'Christian Peetz', 'kunde', 'MFH Memmingen', 215000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"google","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":6100,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":120,"sonstige":0,"kindergeld":876},"ausgaben":{"miete":0,"lebenshaltung":700,"privateKV":350,"zinsTilgung":600,"autokredite":280,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":110}}'::jsonb, 'Tengstr.', '42', '80796', 'München'),
('Carolin', 'Lehmann', '+49 170 2020202', 'c.lehmann@example.de', 'Instagram', 'Christian Peetz', 'kunde', 'MFH Memmingen', 185000, 'positiv', '{"demo":true,"pipelineStufe":"abgeschlossen","leadTyp":"meta","setter":"Lisa Kern","setterCloser":"Christian Peetz","einkuenfte":{"gehalt":5300,"selbstaendig":0,"renten":0,"mieteinnahmen":0,"zinsen":0,"sonstige":0,"kindergeld":438},"ausgaben":{"miete":0,"lebenshaltung":600,"privateKV":0,"zinsTilgung":480,"autokredite":0,"privatkredite":0,"sonstigeKredite":0,"unterhalt":0,"sonstige":80}}'::jsonb, 'Clemensstr.', '17', '80803', 'München');
